---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: doppler-web
  namespace: default
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: doppler
        component: web
        layer: application
      name: doppler-web
    spec:
      containers:
        - name: doppler-web
          env:
            - name: TRACE_AGENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - configMapRef:
                name: doppler-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/doppler:production
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 800Mi
            limits:
              memory: 1Gi
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: tier
                  operator: In
                  values:
                    - foreground

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: doppler
    component: web
    layer: application
  name: doppler-web-internal
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
      targetPort: 8080
  selector:
    app: doppler
    layer: application
    component: web
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: doppler
spec:
  rules:
    - host: developers.artsy.net
      http:
        paths:
          - path: /
            backend:
              serviceName: doppler-web-internal
              servicePort: http
